[package]
name = "pumpkin-protocol"
version.workspace = true
edition.workspace = true

[dependencies]
pumpkin-macros = { path = "../pumpkin-macros" }
pumpkin-world =  { path = "../pumpkin-world" }
pumpkin-core = { path = "../pumpkin-core" }

bytes = "1.7"

uuid.workspace = true

serde = { version = "1.0", features = ["derive"] }
# to parse strings to json responses
serde_json = "1.0"

flate2 = "1.0.33"

thiserror = "1.0.63"
log.workspace = true
num-traits = "0.2"
num-derive = "0.4"

# encryption
aes = "0.8.4"
cfb8 = "0.8.1"
take_mut = "0.2.2"
itertools = "0.13.0"
fastnbt = { git = "https://github.com/owengage/fastnbt.git" }
