[package]
name = "pumpkin-plugin"
version.workspace = true
edition.workspace = true

[features]
default = []
plugins = ["dep:extism"]

[dependencies]
serde.workspace = true
log.workspace = true
extism = { version = "1.6.0", optional = true }
