[package]
name = "pumpkin-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
fastnbt = { git = "https://github.com/owengage/fastnbt.git" }
uuid.workspace = true
colored = "2"
md5 = "0.7.0"
